# MongoDB
#spring.data.mongodb.uri=mongodb://admin:admin@localhost:27017/restaurant?authSource=admin
#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=27017
#spring.data.mongodb.database=restaurant

#PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# MinIO buckets for storing images
minio.url=http://localhost:9000
minio.access-key=minioadmin
minio.secret-key=minioadmin
minio.bucket.name=restaurant-images
preSignedUrlExpirationTimeHours=1
profile-picture-folder=profiles/
location-picture-folder=locations/
dish-picture-folder=dishes/
report-folder=reports/



# AWS credentials
#aws.role_arn=arn:aws:iam::761018851832:role/org/DeveloperAccessRoleTeam4
#aws.session_name=dynamodb
#region=ap-south-1
#access_role=org/DeveloperAccessRoleTeam4
#aws_access_key_id=${AWS_ACCESS_KEY_ID:REDACTED_ACCESS_KEY_ID}
#aws_secret_access_key=${AWS_SECRET_ACCESS_KEY:REDACTED_SECRET_KEY}
#aws_session_token=${AWS_SESSION_TOKEN:REDACTED_SESSION_TOKEN}

#RabbitMQ
#spring.rabbitmq.host=localhost
#spring.rabbitmq.port=5672

#???
#spring.rabbitmq.host=rabbitmq.run7team4-rabbit-dev-rabbit.svc
#spring.rabbitmq.port=5672
#spring.rabbitmq.password=WT86-qyZvxvD5L5Ygv7ifJkt-aT2okh0
#spring.rabbitmq.username=default_user_afy4sMRG3ffR4pzD60_
#???

#rabbitmq.queue.name=restaurant-queue
#rabbitmq.exchange.name=restaurant-exchange
#rabbitmq.routing.key=restaurant-routing-key


