# MongoDB
#spring.data.mongodb.uri=${MONGODB_URL:mongodb+srv://admin-user:mqxOnPsIoxxXPlQz@mongodb-svc.run7team4-db-mongo-env-mongo.svc.cluster.local/admin?replicaSet=mongodb&ssl=false}

# S3 buckets for storing images
#aws.s3.bucket.name=tm4r7-restaurant-dev
#profile-picture-folder=profile/
#location-picture-folder=location/
#dish-picture-folder=dish/
#report-folder=report/
#preSignedUrlExpirationTimeHours=1

# AWS credentials
#aws.role_arn=arn:aws:iam::761018851832:role/org/DeveloperAccessRoleTeam4
#aws.session_name=dynamodb
#region=ap-south-1
#access_role=org/DeveloperAccessRoleTeam4
#aws_access_key_id=${AWS_ACCESS_KEY_ID:REDACTED_ACCESS_KEY_ID}
#aws_secret_access_key=${AWS_SECRET_ACCESS_KEY:REDACTED_SECRET_KEY}
#aws_session_token=${AWS_SESSION_TOKEN:REDACTED_SESSION_TOKEN}


# RabbitMQ credentials
#spring.rabbitmq.host=rabbitmq.run7team4-rabbit-dev-rabbit.svc
#spring.rabbitmq.port=5672
#spring.rabbitmq.password=WT86-qyZvxvD5L5Ygv7ifJkt-aT2okh0
#spring.rabbitmq.username=default_user_afy4sMRG3ffR4pzD60_
#
#rabbitmq.queue.name=restaurant-queue
#rabbitmq.exchange.name=restaurant-exchange
#rabbitmq.routing.key=restaurant-routing-key